[package]
name = "minim-desktop"
description = "minim desktop application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
# The `_lib` suffix keeps the library name distinct from the binary name,
# see https://github.com/rust-lang/cargo/issues/8519
name = "minim_desktop_lib"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true

[lints]
workspace = true
