[package]
name = "minim-desktop"
description = "minim desktop application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
# Le suffixe `_lib` distingue le nom de la bibliothèque de celui du binaire,
# voir https://github.com/rust-lang/cargo/issues/8519
name = "minim_desktop_lib"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
