// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConvertFormat } from "./ConvertFormat";
import type { ExportFormat } from "./ExportFormat";
import type { FieldName } from "./FieldName";
import type { Template } from "./Template";

/**
 * Opération appliquée au document par un workflow.
 */
export type Action = { "type": "rename", 
/**
 * Nouveau nom, avec des variables `{champ}`.
 */
template: Template, } | { "type": "move", 
/**
 * Dossier de destination.
 */
destination: string, 
/**
 * Crée le dossier de destination s'il n'existe pas.
 */
create_folders: boolean, } | { "type": "copy", 
/**
 * Dossier de destination.
 */
destination: string, } | { "type": "convert", 
/**
 * Format cible.
 */
to: ConvertFormat, } | { "type": "extract_fields", 
/**
 * Champs à extraire.
 */
fields: Array<FieldName>, 
/**
 * Format du fichier produit.
 */
output: ExportFormat, };
