// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKind } from "./ActionKind";
import type { ActionStatus } from "./ActionStatus";

/**
 * Trace d'une action au sein d'une exécution.
 */
export type ActionRecord = { 
/**
 * Type de l'action.
 */
type: ActionKind, 
/**
 * Résultat de l'action.
 */
status: ActionStatus, 
/**
 * Durée de l'action en millisecondes.
 */
duration_ms: number, };
