// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type d'une action, sans ses paramètres. Utilisé dans le journal d'exécution.
 */
export type ActionKind = "rename" | "move" | "copy" | "convert" | "extract_fields";
