// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { ErrorDetails } from "./ErrorDetails";

/**
 * Erreur renvoyée à l'interface par une commande Tauri.
 */
export type CommandError = { 
/**
 * Catégorie de l'erreur.
 */
code: ErrorCode, 
/**
 * Clé de traduction du message à afficher.
 */
message_key: string, 
/**
 * Détails structurés, si la catégorie en prévoit.
 */
details?: ErrorDetails, };
