// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldName } from "./FieldName";
import type { MatchMode } from "./MatchMode";
import type { ProfileId } from "./ProfileId";

/**
 * Condition élémentaire d'un déclencheur.
 */
export type Condition = { "type": "file_name_contains", 
/**
 * Texte recherché.
 */
value: string, 
/**
 * Respecte la casse si vrai.
 */
case_sensitive: boolean, } | { "type": "file_name_matches_date", 
/**
 * Format de date attendu ; toute date reconnue convient s'il est absent.
 */
format?: string, } | { "type": "file_extension_is", 
/**
 * Extensions acceptées, sans le point (`pdf`, `png`…).
 */
values: Array<string>, } | { "type": "content_contains_text", 
/**
 * Texte recherché.
 */
value: string, 
/**
 * Respecte la casse si vrai.
 */
case_sensitive: boolean, } | { "type": "content_has_field", 
/**
 * Champ attendu.
 */
field: FieldName, } | { "type": "content_contains_table", 
/**
 * Nombre minimal de lignes du tableau.
 */
min_rows?: number, } | { "type": "similar_to_examples", 
/**
 * Profil appris à partir des documents exemples.
 */
profile_id: ProfileId, 
/**
 * Score de similarité minimal, entre 0 et 1.
 */
threshold: number, } | { "type": "group", 
/**
 * Mode de combinaison des conditions du groupe.
 */
match: MatchMode, 
/**
 * Conditions du groupe.
 */
conditions: Array<Condition>, };
