// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Valeur d'un champ détecté dans un document.
 */
export type DetectedField = { 
/**
 * Valeur lue dans le document.
 */
value: string, 
/**
 * Devise, pour un montant (code ISO 4217 : `EUR`…).
 */
currency?: string, 
/**
 * Confiance de la détection, entre 0 et 1.
 */
confidence: number, };
