// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedField } from "./DetectedField";
import type { DocumentId } from "./DocumentId";
import type { FieldName } from "./FieldName";
import type { FileInfo } from "./FileInfo";
import type { TextSource } from "./TextSource";

/**
 * Résultat de l'analyse d'un document.
 */
export type DocumentProfile = { 
/**
 * Document analysé.
 */
document_id: DocumentId, 
/**
 * Propriétés du fichier.
 */
file: FileInfo, 
/**
 * Origine du texte analysé.
 */
text_source: TextSource, 
/**
 * Champs détectés, par nom.
 */
fields: { [key in FieldName]: DetectedField }, 
/**
 * Le document contient au moins un tableau.
 */
has_tables: boolean, 
/**
 * Mots-clés significatifs du document.
 */
keywords: Array<string>, };
