// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IoErrorKind } from "./IoErrorKind";
import type { ValidationError } from "./ValidationError";

/**
 * Détails structurés d'une erreur, selon sa catégorie.
 */
export type ErrorDetails = { "kind": "validation", 
/**
 * Problèmes trouvés.
 */
issues: Array<ValidationError>, } | { "kind": "io", 
/**
 * Nature de l'erreur.
 */
io_kind: IoErrorKind, };
