// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Catégorie stable d'une erreur, sérialisée en `snake_case`.
 */
export type ErrorCode = "validation_failed" | "not_found" | "io" | "internal";
