// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionRecord } from "./ActionRecord";
import type { DocumentId } from "./DocumentId";
import type { ExecutionStatus } from "./ExecutionStatus";
import type { RunId } from "./RunId";
import type { WorkflowId } from "./WorkflowId";

/**
 * Entrée du journal pour une exécution de workflow sur un document.
 */
export type ExecutionLog = { 
/**
 * Identifiant de l'exécution.
 */
id: RunId, 
/**
 * Document traité.
 */
document_id: DocumentId, 
/**
 * Workflow exécuté.
 */
workflow_id: WorkflowId, 
/**
 * Version du workflow au moment de l'exécution.
 */
workflow_version: number, 
/**
 * Résultat global.
 */
status: ExecutionStatus, 
/**
 * Actions exécutées, dans l'ordre.
 */
actions: Array<ActionRecord>, 
/**
 * Message d'erreur si l'exécution a échoué.
 */
error: string | null, 
/**
 * Début de l'exécution.
 */
started_at: string, };
