// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Résultat global d'une exécution.
 */
export type ExecutionStatus = "success" | "failed" | "sent_to_waiting_zone";
