// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Format du fichier produit par une extraction de champs.
 */
export type ExportFormat = "csv" | "json";
