// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nom d'un champ : une lettre minuscule ASCII suivie de minuscules, chiffres
 * ou `_`.
 *
 * La liste des champs reste ouverte : de nouveaux champs apparaissent avec les
 * capacités d'analyse, sans changement du modèle.
 */
export type FieldName = string;
