// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Propriétés du fichier d'un document.
 */
export type FileInfo = { 
/**
 * Nom du fichier, extension comprise.
 */
name: string, 
/**
 * Extension, sans le point.
 */
extension: string, 
/**
 * Taille en octets.
 */
size: number, };
