// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nature d'une erreur d'entrée-sortie, sans le message du système.
 */
export type IoErrorKind = "not_found" | "permission_denied" | "already_exists" | "storage_full" | "other";
