// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mode de combinaison des conditions d'un déclencheur.
 */
export type MatchMode = "all" | "any";
