// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Résultat de l'évaluation d'un déclencheur sur un profil de document.
 */
export type MatchResult = "match" | "no_match" | "uncertain";
