// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifiant d'une organisation, c'est-à-dire d'un compte entreprise (`org_…`).
 */
export type OrganizationId = string;
