// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrganizationId } from "./OrganizationId";
import type { UserId } from "./UserId";

/**
 * Propriétaire d'un workflow.
 */
export type Owner = { "kind": "user", "id": UserId } | { "kind": "organization", "id": OrganizationId };
