// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifiant d'un profil appris à partir de documents exemples (`prf_…`).
 */
export type ProfileId = string;
