// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifiant d'une exécution de workflow (`run_…`).
 */
export type RunId = string;
