// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Modèle de texte analysé.
 *
 * Sérialisé sous forme de texte source ; la désérialisation refuse un modèle
 * invalide.
 */
export type Template = string;
