// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { MatchMode } from "./MatchMode";
import type { TriggerSource } from "./TriggerSource";

/**
 * Déclencheur d'un workflow : des conditions combinées par `all` (ET) ou
 * `any` (OU), éventuellement regroupées (voir [`Condition::Group`]).
 */
export type Trigger = { 
/**
 * Mode de combinaison des conditions.
 */
match: MatchMode, 
/**
 * Conditions évaluées sur le profil du document.
 */
conditions: Array<Condition>, 
/**
 * Origine du déclencheur.
 */
source: TriggerSource, };
