// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Problème qui empêche d'enregistrer ou d'exécuter un workflow.
 *
 * Sérialisé avec un champ `code` pour que l'interface affiche un message
 * traduit ; les index de conditions et d'actions commencent à 0.
 */
export type ValidationError = { "code": "unsupported_schema_version", 
/**
 * Version trouvée dans le workflow.
 */
found: number, } | { "code": "empty_name" } | { "code": "name_too_long", 
/**
 * Longueur maximale, en caractères.
 */
max: number, } | { "code": "zero_version" } | { "code": "updated_before_created" } | { "code": "no_conditions" } | { "code": "empty_search_text", 
/**
 * Index de la condition.
 */
index: number, } | { "code": "empty_date_format", 
/**
 * Index de la condition.
 */
index: number, } | { "code": "no_extensions", 
/**
 * Index de la condition.
 */
index: number, } | { "code": "invalid_extension", 
/**
 * Index de la condition.
 */
index: number, 
/**
 * Extension refusée.
 */
extension: string, } | { "code": "zero_min_rows", 
/**
 * Index de la condition.
 */
index: number, } | { "code": "threshold_out_of_range", 
/**
 * Index de la condition.
 */
index: number, } | { "code": "no_actions" } | { "code": "path_separator_in_name", 
/**
 * Index de l'action.
 */
index: number, } | { "code": "empty_destination", 
/**
 * Index de l'action.
 */
index: number, } | { "code": "relative_destination", 
/**
 * Index de l'action.
 */
index: number, } | { "code": "no_fields_to_extract", 
/**
 * Index de l'action.
 */
index: number, };
