// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Problème qui empêche d'enregistrer ou d'exécuter un workflow.
 *
 * Sérialisé à plat : `{ "path": "actions[2]", "code": "empty_destination" }`.
 * Le chemin désigne l'élément concerné (`name`, `trigger.conditions[1]`,
 * `trigger.conditions[1].conditions[0]`, `actions[2]`…), les index commençant
 * à 0. L'interface affiche le message de la clé de traduction
 * `validation.<code>`.
 */
export type ValidationError = { 
/**
 * Chemin de l'élément concerné dans le workflow.
 */
path: string, } & ({ "code": "unsupported_schema_version", 
/**
 * Version trouvée dans le workflow.
 */
found: number, } | { "code": "empty_name" } | { "code": "name_too_long", 
/**
 * Longueur maximale, en caractères.
 */
max: number, } | { "code": "zero_version" } | { "code": "updated_before_created" } | { "code": "no_conditions" } | { "code": "empty_group" } | { "code": "group_too_deep", 
/**
 * Profondeur maximale, niveau du déclencheur compris.
 */
max_depth: number, } | { "code": "empty_search_text" } | { "code": "empty_date_format" } | { "code": "no_extensions" } | { "code": "invalid_extension", 
/**
 * Extension refusée.
 */
extension: string, } | { "code": "zero_min_rows" } | { "code": "threshold_out_of_range" } | { "code": "no_actions" } | { "code": "path_separator_in_name" } | { "code": "empty_destination" } | { "code": "relative_destination" } | { "code": "no_fields_to_extract" });
