// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Owner } from "./Owner";
import type { Trigger } from "./Trigger";
import type { WorkflowId } from "./WorkflowId";

/**
 * Automatisation créée par l'utilisateur.
 */
export type Workflow = { 
/**
 * Version du schéma JSON du workflow. Absente dans les workflows écrits
 * avant son introduction, elle vaut alors 1.
 */
schema_version: number, 
/**
 * Identifiant du workflow.
 */
id: WorkflowId, 
/**
 * Nom affiché.
 */
name: string, 
/**
 * Incrémenté à chaque modification ; sert à la synchronisation. Commence à 1.
 */
version: number, 
/**
 * Un workflow désactivé n'est pas évalué.
 */
enabled: boolean, 
/**
 * Ordre d'évaluation : plus petit = évalué en premier (D-10).
 */
priority: number, 
/**
 * Si vrai, le workflow suivant est aussi évalué après une correspondance (D-10).
 */
continue_on_match: boolean, 
/**
 * Déclencheur qui reconnaît les documents concernés.
 */
trigger: Trigger, 
/**
 * Actions exécutées dans l'ordre.
 */
actions: Array<Action>, 
/**
 * Propriétaire du workflow.
 */
owner: Owner, 
/**
 * Date de création.
 */
created_at: string, 
/**
 * Date de dernière modification.
 */
updated_at: string, };
